"use strict";(()=>{var e={};e.id=762,e.ids=[762],e.modules={517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},3419:(e,t,r)=>{r.r(t),r.d(t,{headerHooks:()=>d,originalPathname:()=>g,patchFetch:()=>b,requestAsyncStorage:()=>p,routeModule:()=>f,serverHooks:()=>m,staticGenerationAsyncStorage:()=>c,staticGenerationBailout:()=>y});var a={};r.r(a),r.d(a,{GET:()=>u});var n=r(5419),o=r(9108),s=r(9678),i=r(3022),l=r(7252);async function u(){let e=await {name:"BudtziTools",short_name:"BudtziTools",start_url:".",display:"standalone",background_color:"#020617",description:"A readable Hacker News app.",icons:[{src:"manifest-icon-192.maskable.png",sizes:"192x192",type:"image/png",purpose:"any"},{src:"manifest-icon-192.maskable.png",sizes:"192x192",type:"image/png",purpose:"maskable"},{src:"manifest-icon-512.maskable.png",sizes:"512x512",type:"image/png",purpose:"any"},{src:"manifest-icon-512.maskable.png",sizes:"512x512",type:"image/png",purpose:"maskable"}],theme_color:"#020617"},t=(0,l.resolveRouteData)(e,"manifest");return new i.NextResponse(t,{headers:{"Content-Type":"application/manifest+json","Cache-Control":"public, max-age=0, must-revalidate"}})}let f=new n.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/manifest.webmanifest/route",pathname:"/manifest.webmanifest",filename:"manifest",bundlePath:"app/manifest.webmanifest/route"},resolvedPagePath:"next-metadata-route-loader?page=%2Fmanifest.webmanifest%2Froute&filePath=C%3A%5CUsers%5Crfmal%5CDesktop%5CPraktik%5Cbudtz_toolbox_ts%5Csrc%5Capp%5Cmanifest.ts&isDynamic=1!?__next_metadata_route__",nextConfigOutput:"",userland:a}),{requestAsyncStorage:p,staticGenerationAsyncStorage:c,serverHooks:m,headerHooks:d,staticGenerationBailout:y}=f,g="/manifest.webmanifest/route";function b(){return(0,s.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:c})}},7252:(e,t,r)=>{Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveRobots:function(){return n},resolveSitemap:function(){return o},resolveManifest:function(){return s},resolveRouteData:function(){return i}});let a=r(9926);function n(e){let t="";for(let r of Array.isArray(e.rules)?e.rules:[e.rules]){for(let e of(0,a.resolveArray)(r.userAgent||["*"]))t+=`User-Agent: ${e}
`;if(r.allow)for(let e of(0,a.resolveArray)(r.allow))t+=`Allow: ${e}
`;if(r.disallow)for(let e of(0,a.resolveArray)(r.disallow))t+=`Disallow: ${e}
`;r.crawlDelay&&(t+=`Crawl-delay: ${r.crawlDelay}
`),t+="\n"}return e.host&&(t+=`Host: ${e.host}
`),e.sitemap&&(0,a.resolveArray)(e.sitemap).forEach(e=>{t+=`Sitemap: ${e}
`}),t}function o(e){let t="";for(let r of(t+='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n',e)){if(t+=`<url>
<loc>${r.url}</loc>
`,r.lastModified){let e=r.lastModified instanceof Date?r.lastModified.toISOString():r.lastModified;t+=`<lastmod>${e}</lastmod>
`}r.changeFrequency&&(t+=`<changefreq>${r.changeFrequency}</changefreq>
`),"number"==typeof r.priority&&(t+=`<priority>${r.priority}</priority>
`),t+="</url>\n"}return t+"</urlset>\n"}function s(e){return JSON.stringify(e)}function i(e,t){return"robots"===t?n(e):"sitemap"===t?o(e):"manifest"===t?s(e):""}},9926:(e,t)=>{function r(e){return Array.isArray(e)?e:[e]}function a(e){if(null!=e)return r(e)}Object.defineProperty(t,"__esModule",{value:!0}),function(e,t){for(var r in t)Object.defineProperty(e,r,{enumerable:!0,get:t[r]})}(t,{resolveAsArrayOrUndefined:function(){return a},resolveArray:function(){return r}})}};var t=require("../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),a=t.X(0,[638,5],()=>r(3419));module.exports=a})();